#插件前綴
Prefix: "[AutoFishing]"

CommandMessage:
  Reload: "插件重新加載完成。"
  Enabled_AutoFishing: "成功啟用自動釣魚。"
  Disabled_AutoFishing: "成功關閉自動釣魚。"
  NoPermission: "沒有使用該命令的許可權。"
  NotPlayer: "該指令無法在後台運行。"

AutoFishingSetting:
  #魚咬餌後，在多少個 Tick 內釣起。
  #若超過 25Tick 可能會導致釣魚失敗。
  Ticks_After_Bitten: 5

  #在釣起魚後，間隔多少個 Tick 再次甩竿。
  Ticks_After_Caught: 20